# Generated by Django 4.0 on 2022-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaComodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaCor', models.CharField(max_length=20, verbose_name='Nome da Cor')),
                ('codigoDaCor', models.CharField(max_length=10, verbose_name='Cor')),
                ('corDoTexto', models.CharField(max_length=20, verbose_name='Cor do Texto')),
                ('categoriaDaCor', models.CharField(choices=[(1, 'Prontas'), (2, 'Color System')], max_length=20, verbose_name='Cor do Texto')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('tituloDaPagina', models.CharField(max_length=50, verbose_name='Título da Página')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('siglaEstado', models.CharField(max_length=3, verbose_name='Sigla do Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('referencia', models.CharField(max_length=20, verbose_name='Referência')),
                ('CodigoDaCor', models.CharField(max_length=20, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('siglaEstado', models.CharField(max_length=3, verbose_name='Sigla do Estado')),
            ],
        ),
    ]
